export default {
    MAX_PLAYERS_PER_GAME: 2,
    NUM_CARDS_DRAWN_PER_TURN: 2,
    MAX_CARDS_PER_HAND: 4,
    NUM_CARDS_DRAWN_AT_GAME_START: 4,
    NUM_PLAYER_MOVES_PER_TURN: 4,
    GAME_ACTION_LIMIT: 20
};
