export const GAME_REGISTER_PLAYER = 'GAME_REGISTER_PLAYER';
export const GAME_START = 'GAME_START';
export const GAME_STATUS_INIT = 'GAME_STATUS_INIT';
export const GAME_STATUS_RUNNING = 'GAME_STATUS_RUNNING';
export const GAME_STATUS_WIN = 'GAME_STATUS_WIN';
export const GAME_STATUS_LOSE = 'GAME_STATUS_LOSE';
export const GAME_SPEND_PLAYER_MOVE = 'GAME_SPEND_PLAYER_MOVE';
