export const GAME_REGISTER_PLAYER = "GAME_REGISTER_PLAYER";
export const GAME_START = "GAME_START";
export const GAME_END = "GAME_END";
export const GAME_STATUS_INIT = "GAME_STATUS_INIT";
export const GAME_STATUS_RUNNING = "GAME_STATUS_RUNNING";
export const GAME_STATUS_END = "GAME_STATUS_END";
export const GAME_SPEND_MOVE = "GAME_SPEND_MOVE";
export const GAME_CYCLE_TO_NEXT_PLAYER = "GAME_CYCLE_TO_NEXT_PLAYER";
export const GAME_END_TURN = "GAME_END_TURN";
export const GAME_RESET = "GAME_RESET";

export const RULE_DECK_NOT_EMPTY = "RULE_DECK_NOT_EMPTY";
export const RULE_PLAYER_HAS_CARD = "RULE_PLAYER_HAS_CARD";
export const RULE_IS_SINGLE_MOVE = "RULE_IS_SINGLE_MOVE";
export const RULE_IS_VALID_CODE = "RULE_IS_VALID_CODE";
export const RULE_IS_PRIMITIVE_WRITE = "RULE_IS_PRIMITIVE_WRITE";
export const RULE_IS_VALID_MOVE = "RULE_IS_VALID_MOVE";
