export default {
    GAME_REGISTER_PLAYER: 'GAME_REGISTER_PLAYER',
    GAME_START: 'GAME_START',
    
    GAME_STATUS_INIT: 'GAME_STATUS_INIT',
    GAME_STATUS_RUNNING: 'GAME_STATUS_RUNNING',
    GAME_STATUS_WIN: 'GAME_STATUS_WIN',
    GAME_STATUS_LOSE: 'GAME_STATUS_LOSE'
};
