export const PLAYERS_SET_PLAYER_HAND = "PLAYERS_SET_PLAYER_HAND";
export const PLAYERS_SET_PLAYER_NAME = "PLAYERS_SET_PLAYER_NAME";
export const PLAYERS_REGISTER_PLAYER = "PLAYERS_REGISTER_PLAYER";
export const PLAYERS_GIVE_PLAYER_CARDS = "PLAYERS_GIVE_PLAYER_CARDS";
export const PLAYERS_DISCARD_PLAYER_CARD = "PLAYERS_DISCARD_PLAYER_CARD";
