export const PROMPT_SET_PROMPT = 'PROMPT_SET_PROMPT';
export const PROMPT_SET_TEST_RESULTS = 'PROMPT_SET_TEST_RESULTS';
export const PROMPT_SET_EXAMPLE_TEST_RESULTS = 'PROMPT_SET_EXAMPLE_TEST_RESULTS';
